services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: erp_frontend
    ports:
      - "4200:4200"
    volumes:
      - /frontend/node_modules
      - .:/frontend
