services:
  db:
    build: ./db
    container_name: erp_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: REDACTED
      POSTGRES_PASSWORD: REDACTED
      POSTGRES_DB: erp_db
    ports:
      - "5432:5432"
    # volumes:
    #   - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  backend:
    build:
      context: ./backend
    container_name: erp_backend
    environment:
      DB_HOST: db # Database service name in docker-compose
      DB_PORT: 5432
      DB_NAME: erp_db
      DB_USER: REDACTED
      DB_PASSWORD: REDACTED
    depends_on:
      - db
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: erp_frontend
    ports:
      - "4200:4200"
    volumes:
      - /frontend/node_modules
      - ./frontend:/frontend
    depends_on:
      - backend #optional
