# Generated by Django 6.0.6 on 2026-06-07 21:18

from django.db import migrations


def backfill_category_fk(apps, schema_editor):
    """
    Backfill Product.category_fk from the existing Product.category CharField
    by matching against Product_Categories.category_name.
    """
    Product = apps.get_model("erp", "Product")
    ProductCategories = apps.get_model("erp", "Product_Categories")

    # Build a lookup of category_name -> Product_Categories instance
    category_map = {
        cat.category_name: cat for cat in ProductCategories.objects.all()
    }

    products_to_update = []
    for product in Product.objects.filter(category_fk__isnull=True):
        cat_instance = category_map.get(product.category)
        if cat_instance:
            product.category_fk = cat_instance
            products_to_update.append(product)

    if products_to_update:
        Product.objects.bulk_update(products_to_update, ["category_fk"], batch_size=500)


def reverse_backfill(apps, schema_editor):
    """Reverse: set category_fk back to NULL."""
    Product = apps.get_model("erp", "Product")
    Product.objects.all().update(category_fk=None)


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_data_model_integrity'),
    ]

    operations = [
        migrations.RunPython(backfill_category_fk, reverse_backfill),
    ]
