# Generated by Django 5.2.15 on 2026-06-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_add_original_transaction_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reorder_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
