# Generated by Django 5.2.15 on 2026-06-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='restock',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='restock',
            name='discount_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='restock',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='sales',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='sales',
            name='discount_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
