# Generated by Django 5.2.15 on 2026-06-21 20:17

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_discount_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('LEK', 'Albanian Lek')], max_length=3)),
                ('account_type', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank')], max_length=20)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=20)),
                ('start_date', models.DateField()),
                ('next_due_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('auto_charge', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recurring Expense',
                'verbose_name_plural': 'Recurring Expenses',
                'db_table': 'recurring_expense',
                'ordering': ['next_due_date'],
                'indexes': [models.Index(fields=['next_due_date'], name='rec_exp_next_due_idx'), models.Index(fields=['is_active', 'auto_charge', 'next_due_date'], name='rec_exp_due_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('LEK', 'Albanian Lek')], max_length=3)),
                ('period_date', models.DateField()),
                ('charge_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('REVERSED', 'Reversed')], default='POSTED', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_charges', to='erp.account')),
                ('account_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_charges', to='erp.accounttransaction')),
                ('recurring_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='erp.recurringexpense')),
            ],
            options={
                'verbose_name': 'Expense Charge',
                'verbose_name_plural': 'Expense Charges',
                'db_table': 'expense_charge',
                'ordering': ['-charge_date'],
                'indexes': [models.Index(fields=['-charge_date'], name='exp_charge_date_idx'), models.Index(fields=['period_date'], name='exp_charge_period_idx')],
                'constraints': [models.UniqueConstraint(fields=('recurring_expense', 'period_date'), name='unique_expense_period')],
            },
        ),
    ]
