export const environment = {
  production: false,
  apiUrl: "http://0.0.0.0:8080/selita",
  login: "/login",
  refreshToken: "/api/token/refresh/",
  addProduct: "/add-product",
  getProducts: "/products",
  getProductCategories: "/product-categories",
  getProductNames: "/product-names",
  filterByCategories: "/filterbycategories",
  getSales: "/salesinfo",
  productbyid: "/productbyid",
  getClients: "/clients",
  paySale: "/pay-sale/",
  getClientById: "/client/",
};
