export const environment = {
  production: false,
  apiUrl: "http://localhost:8080/selita",
  login: "/login",
  refreshToken: "/api/token/refresh/",
  addProduct: "/add-product",
  getProducts: "/products",
  getProductCategories: "/product-categories",
  getProductNames: "/product-names",
  updatePrice: "/update-price/",
  filterByCategories: "/filterbycategories",
  getSales: "/salesinfo",
  productbyid: "/productbyid",
  getClients: "/clients",
  paySale: "/pay-sale/",
  createSale: "/create-sale",
  updateInventory: "/update-inventory",
  checkdisponibility: "/checkdisponibility/",
  getClientById: "/client/",
  addClient: "/add-client",
};
